services:
  # Web service to keep the API alive and manage products
  - type: web
    name: price-tracker-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: MONGODB_URI
        sync: false

  # Background worker with built-in cron (runs continuously)
  - type: worker
    name: price-checker-worker
    env: node
    buildCommand: npm install
    startCommand: npm run cron
    envVars:
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
      - key: MONGODB_URI
        sync: false
