name: Price Check Cron Job

on:
  schedule:
    # Runs every 5 minutes
    - cron: '0 */4 * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  check-prices:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install
      
      - name: Run price checker
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
        run: node checkPricesOnce.js
